name: E2E tests
description: Run E2E tests

inputs:
  url:
    description: 'Url to run the E2E test'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Show env
      run: |
        echo "Running tests on: $E2E_BASE_URL"
        npm run test:e2e
      shell: bash
      env:
        E2E_BASE_URL: ${{ inputs.url }}
