name: E2E tests
description: Run E2E tests

runs:
  using: 'composite'
  steps:
    - name: Show env
      env:
        CI: true
        E2E_BASE_URL: ${{ env.DEPLOY_URL }}
      run: |
        echo "Running tests on: $E2E_BASE_URL"
        npm run test:e2e
      shell: bash
