name: E2E tests
description: Run E2E tests

runs:
  using: 'composite'
  steps:
    - name: Show env
      run: |
        echo "Running tests on: $E2E_BASE_URL"
        npm run test:e2e
      shell: bash
      env:
        CI: true
        E2E_BASE_URL: $E2E_BASE_URL
