name: E2E tests
description: Run E2E tests

runs:
  using: 'composite'
  steps:
    - name: Show env
      run: |
        echo "Base URL: $DEPLOY_URL"
        npm run BASE_URL=$DEPLOY_URL test:e2e
      shell: bash
