name: Stepup Project
description: Setpu node Project

runs:
  using: 'composite'
  steps:
    - name: Configure node
      uses: actions/setup-node@v4
      with:
        node-verision-file: ./.nvmrc

    - name: Install dependencies
      run: npm ci
      shell: bash
