name: Deploy - AWS

on:
  workflow_disptch:

jobs:
  deploy-aws:
    environment:
      name: 'Production'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Lint code
        run: npm run lint

      - name: Run code formatting check and unit tests
        uses: ./.github/actions/CodeFormatting-and-unit-test

      - name: Build app
        run: npm run build
        env:
          VITE_ENVIRONMENT: ${{'Production'}}

      - name: Deploy to AWS
        run: aws s3 sync dist/ s3://mc-rmcatalog-pg
